# Generated by Django 6.0.5 on 2026-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Alta', 'Alta'), ('Mitjana', 'Mitjana'), ('Baixa', 'Baixa')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
